app/models.py
from . import db
from datetime import datetime


class Type(db.Model):
    __tablename__ = 'types'
    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)


class Category(db.Model):
    __tablename__ = 'categories'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    images = db.relationship('Image', backref='cate', lazy='dynamic')
    count = db.Column(db.Integer, default=0)
    conver_url = db.Column(db.String)

    def add_one(self, filename):
        if self.count:
            self.count += 1
        else:
            # init value as integer
            self.count = 1
            self.conver_url = filename


class Image(db.Model):
    __tablename__ = 'images'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    filename = db.Column(db.String)
    category = db.Column(db.String)
    sextype = db.Column(db.String)
    url = db.Column(db.String)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    category_id = db.Column(db.Integer, db.ForeignKey('categories.id'))

app/gallery/forms.py
# coding=utf-8
from flask.ext.wtf import Form
from wtforms import StringField, PasswordField, BooleanField, SubmitField, IntegerField, SelectField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.validators import Required, Email, Length, Regexp, EqualTo, Optional, DataRequired
from wtforms import ValidationError
from flask_wtf.file import FileField
from ..models import Category


def enabled_categories():
    return Category.query.all()


class ImageForm(Form):
    name = StringField(u'衣服名称', validators=[Length(1, 64)])
    category = QuerySelectField(u'服装分类', query_factory=enabled_categories, get_label='name', allow_blank=True,
                                validators=[DataRequired()])

    @classmethod
    def category_choice(cls):
        choices = [(x.id, str(x.name)) for x in Category.query.all()]
        cls.lazy_value = choices

    image = FileField(u'衣服图像', validators=[Required(), DataRequired()])
    submit = SubmitField(u'添加一件')


class CategoryForm(Form):
    name = StringField(u'新的服饰分类', validators=[Length(1, 64)])
    sextype = SelectField(u'服饰选择', choices=[('boy', u'男装'), ('girl', u'女装'), ('part', u'配件')])
    submit = SubmitField(u'添加')

app/__init__.py
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.sqlalchemy import SQLAlchemy
from config import config
from log import create_logger

bootstrap = Bootstrap()
db = SQLAlchemy()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    db.init_app(app)

    from .gallery import gallery as gallery_blueprint
    app.register_blueprint(gallery_blueprint, url_prefix='/gallery')

    # import logging
    # handler = create_logger('/var/log/gallery.log', level=logging.INFO)
    # app.logger.addHandler(handler)

    return app

app/gallery/__init__.py
from flask import Blueprint

gallery = Blueprint('gallery', __name__)

from . import views

app/gallery/views.py
# coding=utf-8
import os
from flask import render_template, redirect, request, flash, current_app, url_for, abort, send_from_directory
from werkzeug import secure_filename
from . import gallery
from .forms import ImageForm, CategoryForm
from ..models import Image, Category
from app import db


@gallery.route('/')
def index():
    return render_template('gallery/index.html')


@gallery.route('/add-category', methods=['GET', 'POST'])
def add_category():
    form = CategoryForm()
    if request.method == 'POST':
        if form.name.data:
            category_name = form.name.data
            category = Category(name=category_name)
            db.session.add(category)
            db.session.commit()
            return redirect(url_for('gallery.upload'))
        else:
            return redirect(url_for('.add_category'))
    return render_template('gallery/add-category.html', form=form)


@gallery.route('/boy/')
def boy():
    albums = Category.query.all()  # Get a list of the Category
    if albums is None:
        abort(404)

    # image = albums[0].images.order_by(Image.timestamp.desc()).first()
    images = []
    for album in albums:
        Image.query.filter_by(category_id=album.id).first()

    size_album = len(albums)
    return render_template('gallery/album.html', size_album=size_album, albums=albums, image=images)


@gallery.route('/girl/')
def girl():
    albums = Category.query.all()  # Get a list of the Category
    if albums is None:
        abort(404)

    # image = albums[0].images.order_by(Image.timestamp.desc()).first()
    images = []
    for album in albums:
        Image.query.filter_by(category_id=album.id).first()

    size_album = len(albums)
    return render_template('gallery/album.html', size_album=size_album, albums=albums, image=images)


@gallery.route('/part/')
def part():
    albums = Category.query.all()  # Get a list of the Category
    if albums is None:
        abort(404)

    # image = albums[0].images.order_by(Image.timestamp.desc()).first()
    images = []
    for album in albums:
        Image.query.filter_by(category_id=album.id).first()

        size_album = len(albums)
    return render_template('gallery/album.html', size_album=size_album, albums=albums, image=images)


@gallery.route('/contact')
def contact():
    return render_template('gallery/contact.html')


@gallery.route('/upload', methods=['GET', 'POST'])
def upload():
    form = ImageForm()
    if request.method == 'POST':
        if form.image.data.filename and form.category.data:
            filename = secure_filename(form.image.data.filename)
            personal_dir = os.path.join(current_app.config['UPLOAD_FOLDER'], str(form.category.data.id))
            if not os.path.exists(personal_dir):
                os.mkdir(personal_dir)

            image_url = os.path.join(personal_dir, filename)
            form.image.data.save(image_url)
            image = Image(name=form.name.data, category=str(form.category.data), url=image_url, filename=filename,
                          category_id=form.category.data.id, sextype=form.sextype.data.id)

            cat = Category.query.filter_by(id=form.category.data.id).first()
            cat.add_one(filename)  # Update the album counter by call instance method!
            db.session.add(cat)
            db.session.add(image)
            db.session.commit()
            return redirect(url_for('gallery.album'))
        else:
            flash(u'请选择一件衣服,才可以上传哦:)')
            return redirect(url_for('.upload'))

    return render_template('gallery/upload.html', form=form)


@gallery.route('/lists/<category_id>')
def lists(category_id):
    album = Category.query.filter_by(id=category_id).first()
    images = album.images.order_by(Image.timestamp.desc())
    return render_template('gallery/lists.html', images=images)


@gallery.route('/heads/<category>/<filename>')
def send_image(category, filename):
    # personal_dir = os.path.join(current_app.config['UPLOAD_FOLDER'], category)
    personal_dir = current_app.config['UPLOAD_FOLDER'] + '/' + category + '/'
    return send_from_directory(personal_dir, filename)

app/templates/_nav.html
<div class="navbar navbar-inverse navbar-static-top">
    <div class="navbar-inner">
        <div class="container">
            <ul class="nav">
                <li>
                    <a href="{{ url_for('gallery.index') }}" class="brand"><b>LZ</b></a>
                </li>
                <li class="active">
                    <a href="{{ url_for('gallery.index') }}">模特选择</a>
                </li>
                <li>
                    <a href="{{url_for('gallery.boy')}}">男装</a>
                </li>
                <li>
                    <a href="{{url_for('gallery.girl')}}">女装</a>
                </li>
                <li>
                    <a href="{{url_for('gallery.part')}}">服饰配件</a>
                </li>
                <!--
                <li >
                    <a href="/blog/">Blog</a>
                </li>
                -->

                <li>
                    <a href="{{ url_for('gallery.upload') }}">添加衣服</a>
                </li>
                <li>
                    <a href="{{ url_for('gallery.contact') }}">联系</a>
                </li>
            </ul>
        </div>
    </div>
</div>

app/templates/base.html
<!DOCTYPE html>
<html lang="en-US">
<head>
    {% block head %}
    <link rel="icon" type="image/png" href="http://media.tylergriffinphotography.com/img/favicon.png"/>
    <title>Home :: LZ</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="google-site-verification" content="fFSB2Uapxdane0mHui9_hUrg8Ac_loOLMufnNnh2TFs"/>

    <link rel="stylesheet" href="{{url_for('static',filename='css/typography.css')}} " type="text/css"
          media="screen,projection"/>
        <link rel="stylesheet" href="{{url_for('static',filename='css/custom.css')}}" type="text/css"
          media="screen,projection"/>
    <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.min.css')}}" type="text/css"
          media="screen,projection"/>

    <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap-resp.min.css')}}" type="text/css"
          media="screen,projection"/>
    <link rel="alternate" href="http://tylergriffinphotography.com/blog/feed/" title="RSS" type="application/rss+xml"/>
    <script src="{{url_for('static',filename='js/mint.js') }}" type="text/javascript"></script>
    <script src="{{url_for('static',filename='js/jquery.min.js')}} " type="text/javascript"></script>
    <script src="{{ url_for('static',filename='js/bootstrap.min.js')}} " type="text/javascript"></script>
    {% endblock %}
</head>
<body>
{% include "_nav.html" %}
</div>
<!--
<div id="logo">
    <a href="/"><img src="http://media.tylergriffinphotography.com/img/logo.png" alt="Tyler Griffin Photography" /></a>
</div>
-->
<div class="container main">

    {% block content %}

    {% endblock %}


</div>
<footer>
    <div class="container center">
        Copyright &copy; 2016 , LZ . All Rights Reserved
    </div>
</footer>
</body>
</html>

app/templates/gallery/add-category.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block content %}

{{ wtf.quick_form(form)}}

{% endblock %}

app/templates/gallery/album.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <ul class="thumbnails">

        {% for index in range(size_album) %}

        {% if albums[index].count > 0 %}
        <li class="gallery span1">
            <a href="{{ url_for('gallery.lists',category_id=albums[index].id) }}" class="thumbnail">
                {% with path = '1/imut2.jpg' %}
                <img src="{{ url_for('gallery.send_image',category=albums[index].id,filename=albums[index].conver_url )}}" alt=""
                     class="span1"/>

                {% endwith %}
                <h5>{{ albums[index].name }}</h5>
            </a>
        </li>
        {% endif %}
        {% endfor %}


    </ul>
</div>

{% endblock %}

app/templates/gallery/contact.html
{% extends "base.html" %}


{% block content %}
<form method="post" action="/contact/">
    <table cellspacing="0" cellpadding="0" style="border:none;width:400px;margin:0 auto;">
        <tr>
            <th><label for="id_name">Name:</label></th>
            <td><input id="id_name" type="text" name="name" maxlength="128"/></td>
        </tr>
        <tr>
            <th><label for="id_email">Email:</label></th>
            <td><input type="text" name="email" id="id_email"/></td>
        </tr>
        <tr>
            <th><label for="id_subject">Subject:</label></th>
            <td><input id="id_subject" type="text" name="subject" maxlength="128"/></td>
        </tr>
        <tr>
            <th><label for="id_body">Body:</label></th>
            <td><textarea id="id_body" rows="10" cols="40" name="body"></textarea></td>
        </tr>
        <tr>
            <th></th>
            <td><input type="submit" id="btn" name="btn" value="Send"/></td>
        </tr>
    </table>
</form>

{% endblock %}

app/templates/gallery/index.html
{% extends "base.html" %}


{% block nav %}
{{super()}}
{% endblock %}

{% block content %}
<img src="{{ url_for('static',filename='img/model.png')}}"
     alt="Tyler Griffin Photography" class="img-polaroid"/>

{% endblock %}

app/templates/gallery/lists.html
{% extends "base.html" %}

{% block content %}

<div id="gallery-title">
    <h2>Headshots</h2>
    <a href="/gallery/album/">&laquo; Back to Portfolio</a>
</div>


<div class="gallery masonry">
    {% for image in images %}
    <div class="box photo masonry-brick">
        <a href="#" class="thumbnail">
            <img src="{{ url_for('gallery.send_image',category=image.category_id,filename=image.filename) }}"
                 alt="{{ image.name }}"/>
        </a>
    </div>

    {% endfor %}

</div>
<div class="modal hide fade" id="lightbox">
    <div class="modal-body">
    </div>
</div>

<script src="{{url_for('static',filename='js/masonry.min.js')}} "></script>
<script>
    $(function () {
        var $gallery = $('.gallery');
        $gallery.imagesLoaded(function () {
            $gallery.masonry({
                itemSelector: '.box',
                columnWidth: function (containerWidth) {
                    return containerWidth / 3;
                }
            });
        });

        var lightbox = $('#lightbox');
        var inner = lightbox.find('.modal-body');

        inner.css({maxHeight: 'none'});

        $('.thumbnail').click(function (e) {
            e.preventDefault();
            var img = $('<img>').attr({src: $(this).find('img').attr('src')});
            img.bind('load', function () {
                var el = img[0];
                var width = el.width;
                var height = el.height
                var factor = 1.0;
                if (height > $(window).height() * 0.8) {
                    factor = $(window).height() * 0.8 / el.height;
                }
                else if (width > $(window).width() * 0.8) {
                    factor = $(window).width() * 0.8 / el.width;
                }
                height = parseInt(height * factor);
                width = parseInt(width * factor);
                lightbox.css({
                    width: width + 30,
                    marginTop: height / -2,
                    marginLeft: width / -2
                });
            });
            inner.empty();
            inner.append(img);
            lightbox.modal();
        });
    });
</script>


{% endblock %}

app/templates/gallery/upload.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block content %}

{{ wtf.quick_form(form,enctype="multipart/form-data")}}
<br>
<p>
    是否需要添加衣服分类?
    <a href="{{ url_for('gallery.add_category') }}">
        点击这里添加衣服分类
    </a>
</p>

{% endblock %}